### ISSUE TITLE
Test data not available

### ISSUE THREAD

**Issue by zovelsanj** [eelregit/map2map#10]
I am trying to replicate this work and I have no data. Is at least the test data available?

**Comment by eelregit** [comment]
Which test data did you refer to? Anyway it's good to see that the problem seemed to be resolved for you.

**Comment by zovelsanj** [comment]
> Which test data did you refer to? Anyway it's good to see that the problem seemed to be resolved for you.

I was referring to the style-GAN test dataset for N-body cosmological simulations. I also contacted Dr. @sbird and he provided me the link to MP-Gadget which was used for data generation. In case you have a small chunk of test dataset (a few GBs) and per-trained model, it would be great.

**Comment by eelregit** [comment]
If you were referring to the super-resolution one, Yueying's repo is here: https://github.com/yueyingn/SRS-map2map
Though I don't know if we still hold the simulations data. IIRC, we uploaded the trained weights to https://www.pnas.org/doi/10.1073/pnas.2022038118 in the supporting information.

**Comment by zovelsanj** [comment]
Thank you very much.
