### ISSUE TITLE
def assemble in fields.py not implemented for scale factor > 1?

### ISSUE THREAD

**Issue by diveshjain-phy** [eelregit/map2map#11]
Hi! I went through all of the 3 papers that use map2map, but I did not understand how to assemble the small chunks/crops to get back the complete SR field. The implementation of function assemble in class FieldDataset has a flag for scale factor > 1.

**Comment by eelregit** [comment]
Hi! It seems that the assemble method has not been implemented for super-resolution. I probably wrote it to help to assemble automatically for the other projects. However, it should be straightforward to tile manually or write your own assemble function if you have all your dimensions fixed.

**Comment by diveshjain-phy** [comment]
Thanks for your response. I understand; I was able to do it.
