### ISSUE TITLE
Training/model details as mentioned in paper?

### ISSUE THREAD

**Issue by tvhahn** [eelregit/map2map#6]
Great work. I enjoyed reading your paper "AI-assisted superresolution cosmological simulations". 

Unless I'm wrong, I can't see what parameters and model combinations you used to create your super-resolutions images (only general examples in the model folder). It would help me (and I'm sure others) if you could include those as an example. That way I can read the paper, and look at the code, and see what is happening.

Thanks!

**Comment by tvhahn** [comment]
Is the `srsgan.py` the implementation that you use to generate your results?

**Comment by eelregit** [comment]
Thanks!

The code is written to do general field to field mapping. Super resolution is a special case here, activated by the `--scale-factor` option.

You are right that we used the models in `srsgan.py` for our paper, using the `wgan` branche and `--scale-factor 8`.
