### ISSUE TITLE
李老师您好，我是于洋，有意向报名您的的博士。

### ISSUE THREAD

**Issue by yy2lxx** [eelregit/map2map#9]
李老师您好，我是中国科学院大学计算机专业研三的学生于洋。

 

   因为对天文有浓厚的兴趣，从初中时就已经把天文当成爱好坚持了十多年并成立过天文社团，所以在研究生期间自学了如普通物理（同济版），天体物理（北大徐仁新老师），初等量子力学（大卫.格里菲斯）等相关课程。目前通过自学我已经具有一名普通天文学研究生应有的学术背景与能力。

 

   目前已发表两篇EI论文，一篇EI检索IEEE出版的星系形态分类论文《Galaxy Morphology Classification Based On ResNeXt》，另一篇EI检索ACM出版的硕士毕业要求的小论文《Handwritten Chinese Character Recognition Based on Swin Transformer Network》。

 

   去年我还参加了由国家天文台和多所高校联合开展的2021深度学习在天文大数据中的应用会议，并且我与国家天文台的老师学生们合作，共同翻译了美国科学院发布的Astronomy and Astrophysics for the 2020s（2020年代天文学与天体物理的发现之路）。

 

   此外，在大学毕业后，我做过两年的高中物理老师。2018年到2020年期间，我在北京的教培机构帮助高中生提高物理成绩，这两年一共带过40多位高中生。

 

   有意向报名知识网络研究室的博士。请问您今年是否招博士生？我从哪里可以找到我们研究室的招生信息？感谢您百忙之中看到我给您发的邮件，我的联系方式是：13126989211（电话/微信）。

**Comment by eelregit** [comment]
于洋您好，我去问了一下：明年入学的招生已经结束了，只有后年的。而且我们全职的现在还不能招收博士生，只有双聘的老师可以，以后规矩也许会变。我没搜到你的Resnext的论文，对morphology也很感兴趣。

我在想你能不能去申一下港科大广州与IDEA的联合项目，通过了的话我们可以跟沈老师和IDEA的人一起合作。
[应该是这个项目](https://mp.weixin.qq.com/s?__biz=MzkzODI5MDE2NA==&mid=2247488239&idx=1&sn=0cdefb409e6eaea05f1496faa6538a93&chksm=c2832c74f5f4a5628a33b84413c4509f99dff7a5ca10972ac7bc9d337e7c9ad963d975be0747&srcid=0704cqUixqlPfwStiunZ4pnL)

**Comment by yy2lxx** [comment]
李老师您好，附件里是我的论文，目前已被录用但是还未见刊。
感谢您给我提供的信息，我今天看了港科大idea联合项目的官网，报名条件里要求的英语雅思托福成绩我目前没有，我正在考虑准备两到三个月争取考个雅思6.5分，如果到时候能达到报名要求，我准备报名港科大idea联合项目。
还想请教您，除了港科大这个项目，在天文+ai方向您还有其他推荐的学校吗？如果有不要求雅思托福成绩的学校，我能直接报名就更好了，感谢您。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eelregit/map2map"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 中午1:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eelregit/map2map] 李老师您好，我是于洋，有意向报名您的的博士。 (Issue #9)





 
于洋您好，我去问了一下：明年入学的招生已经结束了，只有后年的。而且我们全职的现在还不能招收博士生，只有双聘的老师可以，以后规矩也许会变。我没搜到你的Resnext的论文，对morphology也很感兴趣。
 
我在想你能不能去申一下港科大广州与IDEA的联合项目，通过了的话我们可以跟沈老师和IDEA的人一起合作。
 应该是这个项目

**Comment by linan7788626** [comment]
@yy2lxx 你既然是国科大的还想做天文，为什么不考虑一下国家天文台？

**Comment by eelregit** [comment]
就像李楠老师说的，国家天文台在AI方向也很强，他们的空间望远镜项目刚好让你的morphology方面的工作有用武之地。

你的附件可能传不到GitHub上来，不如你给我们俩发邮件吧，我的邮箱是我的用户名@gmail
